### ISSUE TITLE
Pa11y debugging \ results not showing same outcome as HTML codesniffer

### ISSUE THREAD

**Issue by DomSkech** [pa11y/pa11y-dashboard#103]
Hi!

I am using Pa11y dashboard and running pa11y tasks from that. Results are coming back and are suspiciously good! (0 errors or warnings). When I copy the URL it is supposedly hitting from the dashboard and view it in a browser, I am seeing a completely different result when I hit 'HTML codesniffer'

One particular telling one is 'This element has insufficient contrast at this conformance level' which doesn't show at all in pa11y dashboard.

Is there a way I can log the tasks as the execute, or even 'see' the tasks playing out in a normal browser...So I can confirm that it is actually reviewing the correct markup? 

Thanks

D

**Comment by hollsk** [comment]
Hi Dom,

Thanks for reporting this! We have a similar report in #97 which we've been investigating. I can't be 100% sure that your problem is the same as #97 from the information you've given us so far, but one thing will help me nail it down - is the markup that you're testing against loading an iframe with your content in it? 

If that's the case, we'll be able to resolve this when the patch for #97 lands. If not, a sample URL will help us diagnose. 

Thanks!
H

**Comment by DomSkech** [comment]
I am not convinced that there is anything necessarily wrong with Pa11y yet. My theory is that pa11y is getting a 503 or a 404 page and parsing the markup in that, hence the 'clean' results. But I have no way of seeing what pa11y actually sees. This is what I need. Some way to debug, or see the pages as they are tested.

**Comment by DomSkech** [comment]
Hi

I have introduced a deliberate bug onto the page (missing alt tag on image) and run again. It is now showing an error! SO this means that there is something wrong in  Pa11y.

Some of the differences are to do with Javascript injected DOM elements. I have a feeling that Pa11y dashboard runs without javascript and HTML_codesniffer runs in a real browser after javascript has done its thing. 

BUT that still doesn't explain 'This element has insufficient contrast at this conformance level' which is a product of CSS ONLY and should exist with or without JS.

**Comment by rowanmanning** [comment]
Hi @DomSkech, could you try using the [`pa11y` command line tool](https://github.com/springernature/pa11y) with the `--wait` option to check this? It'll tell us whether the issue stems from JavaScript injecting elements into the page:

```
pa11y --wait 1000 yoursite.com
```

pa11y _does_ run JavaScript, but it executes the tests immediately so your JavaScript might not have time to do its thing before the tests are run.

**Comment by DomSkech** [comment]
Interesting... the dashboard returns the error i see in HTML_Codesniffer, even without the --wait.  Which is what I would expect for both that AND dashboard:

 • Error: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 4.49:1. Recommendation: change background to #212121.
   ├── WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
   ├── #mainparsys > div:nth-child(2) > div > div > p > span
   └── <span class="m_first-letter">L</span>

But it doesn't show any of the js born errors. And only goes to further prove that dashboard is not catching the same errors.  

Dashboard is showing 0 errors. 
Pa11y command line showing 2 errors. 
HTML_Codesniffer is showing 13 errors.

**Comment by rowanmanning** [comment]
:scream: is your web page public? It might be easier if one of the maintainers can run these tests and try to diagnose the problem

**Comment by DomSkech** [comment]
No, sadly not. Though perhaps we could demo something via a hangout? If
that's possible you could message me through github?

On 5 Apr 2016 16:22, "Rowan Manning" <notifications@github.com> wrote:
>
> is your web page public? It might be easier if one of the maintainers can
run these tests and try to diagnose the problem
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
<https://github.com/springernature/pa11y-dashboard/issues/103#issuecomment-205855464>

**Comment by DomSkech** [comment]
OK. I have solve half of the problem... DIFFERENT STANDARDS. Duh!

Still am struggling to get JS to be assessed even with the --wait

**Comment by rowanmanning** [comment]
I'm going to close this as the issue's quite old. Now that it's possible to [take screen captures of a page](https://github.com/pa11y/pa11y/pull/240) when you test it, I'd recommend trying that with Pa11y locally.

Feel free to reopen if you're still experiencing the issue and we can discuss.
