### ISSUE TITLE
Create an architectural diagram

### ISSUE THREAD

**Issue by hollsk** [pa11y/pa11y-dashboard#108]
The diagram should show how Pa11y, the Pa11y-webservice, and the Pa11y-dashboard all fit together.

**Comment by hollsk** [comment]
@joseluisbolos has already developed an exploratory idea of what this should look like

**Comment by rowanmanning** [comment]
Do we still want this? I'm thinking _maybe_ not, as it's been open for quite a while and we're replacing the webservice and dashboard. If you disagree we can reopen

**Comment by hollsk** [comment]
not worth it at the moment because of all the changes

we could open a new one later if we need to :-)
