### ISSUE TITLE
Update demo reports to return selectors in JSON/CSV

### ISSUE THREAD

**Issue by hollsk** [pa11y/pa11y-dashboard#112]
Requested here: https://github.com/springernature/pa11y-dashboard/issues/59#issuecomment-122398059

**Comment by rowanmanning** [comment]
Oh this was [added in `1.9.0`](https://github.com/pa11y/dashboard/blob/master/CHANGELOG.md#190-2016-04-25) but I forgot to check for issues. I'm gonna close this :)

**Comment by rowanmanning** [comment]
Oh I see! This is to update the demo site! Sorry. I'll reopen and get on that ASAP

**Comment by rowanmanning** [comment]
Demo site no longer exists, so closing this.
