### ISSUE TITLE
Track Tests based on Milestones/Tags/Deployments/Points/Markers in Time

### ISSUE THREAD

**Issue by StephenOTT** [pa11y/pa11y-dashboard#114]
Would be great if there was a way to add a "tag" to when a test runs and track this against the graphs and test reports.  This would allow you to see when Accessibility issues increase or decrease based on a specific code change.

Is there a way to do this?  Could not find anything in the docs.

**Comment by josebolos** [comment]
Hi @StephenOTT

Unfortunately, this is not possible at the moment. It's definitely in the roadmap though, and we're very interested in making this happen, although it will require a significant amount of work so I don't expect it to happen anytime soon.

**Comment by StephenOTT** [comment]
@joseluisbolos I have not inspected the code heavily, but why is it a significant amount of work?  Ignoring the visuals/graphs for a moment.  Isn't this more about updating the data model with an extra field to store a text value that a user can use to represent/label the point in time when the test(s) are run for the specific website, and then making that field available through the API?

I assume there are complexities that are not apparent?

**Comment by rowanmanning** [comment]
Going to close this as we're not prioritising feature work in Dashboard. If somebody finds this and does the work, we'll still accept a PR.
