### ISSUE TITLE
Make graphs available for download

### ISSUE THREAD

**Issue by josebolos** [pa11y/pa11y-dashboard#115]
Currently pa11y-dashboard uses canvas to generate the graphs - that makes it hard to share the images in a reliable way, download them, or make them available so they can be integrated in other monitor tools and dashboards.

It would be cool if we could provide the graphs as images somehow, as PNGs or maybe even SVGs. It doesn't necessarily have to be the same graph as shown in the screen, a dumbed-down version could be fine.

This would be a significant change so probably better to leave it for the next major release.

**Comment by Rayraegah** [comment]
I have this export graph to PNG and SVG module on my local build of pa11y. I'll give you a PR this weekend. 

I have 2 features, 1 exports the graph to PNG and the other exports the entire page to PNG (opens up all the content panels).

example
![image](https://cloud.githubusercontent.com/assets/1559650/15612338/46133ea4-2426-11e6-866c-62f1a58af1aa.png)

**Comment by una** [comment]
@Rayraegah just curious what the status of this is :) it would be an awesome feature

**Comment by rowanmanning** [comment]
This was added in [v2.4.0](https://github.com/pa11y/pa11y-dashboard/blob/master/CHANGELOG.md#240-2017-11-23)
