### ISSUE TITLE
Look at reducing number of js files

### ISSUE THREAD

**Issue by perryharlock** [pa11y/pa11y-dashboard#12]
There are a number of separate js files being called in.
1 ) Reduce number of files being called. Reduce bootstrap to one minified bootstrap. Same with flot?
2) For @rowanmanning : Could do with these being compiled into a single minified js file for production.

**Comment by perryharlock** [comment]
Concatenate! Concatenate!
Need to concatenate the boostrap js, flot js and site.js files into one.

**Comment by rowanmanning** [comment]
All done
