### ISSUE TITLE
Noob Issue - can't make it work at all :-)

### ISSUE THREAD

**Issue by oddjones** [pa11y/pa11y-dashboard#135]
Hi folks - am I missing something here? Pretty sure I've installed all the dependencies - Pa11y itself runs just fine (insofar as it will pull me down a report from the command line), I've cloned the repo, run the npm install, copied the .json config files, ensured mongo is running (I'm using the bitnami MEAN stack VM on Azure).

I have pa11y installed globally,
node v5.6.0, 
mongodb,3.2.3
phantomJS

When I start the service (ie: NODE_ENV=production node index.js) the services seem to start...

I get shown 
## pa11y-dashboard started

mode: production
uri: http://:::4000
## pa11y-webservice started

mode:production
uri: http://0.0.0.0:3000

but if I browse to the uri, I get nothing - the browser just times out - what am I doing wrong?

**Comment by rowanmanning** [comment]
Hi Dominic, odd that it times out! Normally that would indicate that it's not an error in the application itself. Are you seeing any errors output on the command line?

One thing you could try as a first step is accessing the webservice directly. What happens when you try to access http://localhost:3000/?

**Comment by oddjones** [comment]
the same - nothing

**Comment by oddjones** [comment]
no cli errors

**Comment by oddjones** [comment]
I hasten to add that I'm no linux expert 8-|

**Comment by rowanmanning** [comment]
That suggests that nothing is even hitting the app. I'm not that familiar with the bitnami MEAN stack, so not sure how you're supposed to go about accessing the running app. Is it a VM running locally on your machine?

**Comment by oddjones** [comment]
in azure :-)

**Comment by oddjones** [comment]
apps live in the /opt/bitnami/apps folder - which is where all the other stuff is at

**Comment by rowanmanning** [comment]
Oh right. Hmm, I'll look into this but in the meantime have you tried running locally? Even without the MongoDB database set up? If we can get it outputting pa11y-dashboard errors then that's a good starting point

**Comment by oddjones** [comment]
I'll have a crack at it now - thanks for the speedy reply BTW :-)

**Comment by oddjones** [comment]
I'm stuck behind an authenticated proxy at work which causes no end of problems of its own, but let's see :-)

**Comment by oddjones** [comment]
403 errors locally - what permissions should I set on the folder?

**Comment by rowanmanning** [comment]
Are the 403s in a pa11y-dashboard skin? I.e. with the logo? No worries, I just happened to look at my notifications as you opened this!

**Comment by oddjones** [comment]
erm no - it's giving me a big 500 error when I check the browser (with a server error score of lots!) I'm seeing this at the CLI...

Error: Error 403
    at Request._callback (/Users/dom/pa11y-dashboard/node_modules/pa11y-webservice-client-node/lib/client.js:124:16)
    at Request.self.callback (/Users/dom/pa11y-dashboard/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/dom/pa11y-dashboard/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/dom/pa11y-dashboard/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

(sorry)

**Comment by rowanmanning** [comment]
Don't be 😄 that suggests that maybe the webservice isn't running or the dashboard doesn't have the configuration pointing to the webservice.

Right, at least we have the dashboard actually responding locally. This definitely suggests that Azure needs some extra configuration or something for the dashboard to work. Possibly the port that the dashboard is running on isn't actually exposed in Azure? That'd explain the timeouts.

I'll take a quick look at the docs (possibly this evening though).

**Comment by oddjones** [comment]
absolutely - hometime :-)

**Comment by rowanmanning** [comment]
Not being that familiar with Azure, this might be _completely_ wrong, but do you need to set up any kind of firewall rules? Like this? https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-classic-setup-endpoints/

I think ideally external port 80 traffic should come into your box on port 4000

**Comment by oddjones** [comment]
Yup :-) done that and now I get the same error remotely that I get locally - now that's what I call progress!

**Comment by oddjones** [comment]
Actually, getting this remotely ->

Error: Error 500
    at Request._callback (/opt/bitnami/apps/pa11y-dashboard/node_modules/pa11y-webservice-client-node/lib/client.js:124:16)
    at Request.self.callback (/opt/bitnami/apps/pa11y-dashboard/node_modules/request/request.js:200:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/opt/bitnami/apps/pa11y-dashboard/node_modules/request/request.js:1067:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/opt/bitnami/apps/pa11y-dashboard/node_modules/request/request.js:988:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)

**Comment by rowanmanning** [comment]
Ah cool. So that means that the webservice is responding with a 500 error. Progress! Are you getting no error messages for the webservice?

It might be worth adding a firewall rule to expose port 3000, this is where the webservice should be running. If we can access it directly then we might get a more useful error message.

**Comment by oddjones** [comment]
Hi - sorry to take a while to return, but I was down at localgovcamp -> SO - I have exposed the webservice and it's returning 

{
"statusCode": 404,
"error": "Not Found"
}

**Comment by oddjones** [comment]
(I'm seeing the following on the command line...)

Error: Error 500
    at Request._callback (/opt/bitnami/apps/pa11y-dashboard/node_modules/pa11y-webservice-client-node/lib/client.js:124:16)
    at Request.self.callback (/opt/bitnami/apps/pa11y-dashboard/node_modules/request/request.js:200:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/opt/bitnami/apps/pa11y-dashboard/node_modules/request/request.js:1067:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/opt/bitnami/apps/pa11y-dashboard/node_modules/request/request.js:988:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)

**Comment by oddjones** [comment]
It's also returning a 500 server error when I attempt to post a task.

**Comment by oddjones** [comment]
OK - so I installed it locally on my (home) macbook and I'm getting a totally different set of errors - ('cannot find module 'send' - in CLI on running NODE_env etc)... beginning to lose the will to go on with this guys - anywhere else I can get help?

**Comment by rowanmanning** [comment]
Hi @oddjones: sorry, had a really busy morning so far – no time to help out. Could you paste the (anonymised) contents of your config JSON files here? The fact that the webservice responds with JSON is a good sign, it means it's running.

**Comment by oddjones** [comment]
the config files are exactly the same as the standard ones. I didn't edit them at all (because I didn't know what to edit!)

**Comment by rowanmanning** [comment]
Ah so you have a `config/production.json` file which looks exactly like this?

``` json
{
    "port": 4000,
    "noindex": true,
    "readonly": false,

    "webservice": {
        "database": "mongodb://localhost/pa11y-webservice",
        "host": "0.0.0.0",
        "port": 3000,
        "cron": "0 30 0 * * *"
    }
}
```

It might be worth checking that you can connect to that MongoDB database through the CLI somehow, just to verify that it's there.

**Comment by oddjones** [comment]
Well.. not QUITE :-)

```
{
        "host":"13.94.158.200",
        "port": 4000,
        "noindex": true,
        "readonly": false,
        "siteMessage":"Well, Hello there handsome.",

        "webservice": {
                "database": "mongodb://localhost/pa11y-webservice",
                "host": "0.0.0.0",
                "port": 3000,
                "cron": "0 30 0 * * *"
        }
}
```

**Comment by oddjones** [comment]
Mongo is definitely running - the server is running rockmongo php interface and I can see 2 admin databases and 1 local (although it's just the startup log)

**Comment by oddjones** [comment]
there's no "pa11y-webservice" database

**Comment by rowanmanning** [comment]
Hmm. OK. Definitely running on the default port? Could you try running the following two cURL commands from inside the box and paste the output here? The first one creates a task in the webservice, the second lists all of the tasks:

``` sh
curl -X POST -H "Content-Type: application/json" -d '{"name":"example","url":"http://www.google.com/","standard":"WCAG2AA"}' http://localhost:3000/tasks
```

``` sh
curl -X GET http://localhost:3000/tasks
```

If these work then we can at least narrow down that the problem is in the communication between the webservice and dashboard.

**Comment by oddjones** [comment]
both commands give no response

**Comment by rowanmanning** [comment]
what does `which curl` tell you?

**Comment by oddjones** [comment]
/opt/bitnami/common/bin/curl

**Comment by rowanmanning** [comment]
I'm really stumped. I'd quite like to get you up and running though! Would it be completely out of the question for me to get access to your server temporarily? Feels a bit chinese whispers at the moment 😄

**Comment by oddjones** [comment]
I completely understand - and I have no problem with you jumping on (it's a VM which does nothing else but this)- is there somewhere private I can give you the details?

**Comment by rowanmanning** [comment]
You could join our Slack if you have that? https://pa11y-slack.herokuapp.com/ I won't be able to jump on this right away but should find time this eve or tomorrow.

I'm sorry that your experience getting set up has been painful. We might need to write up some documentation specific to Azure.

**Comment by rowanmanning** [comment]
Are we OK to close this now, @oddjones?

**Comment by oddjones** [comment]
Please do mate, thanks
