### ISSUE TITLE
Export to Sidekick

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y-dashboard#137]
This is a feature for further down the line once [Pa11y Sidekick](https://github.com/pa11y/sidekick) has hit the beta stage. It would be excellent if users of the dashboard could update it and then use a visual interface to migrate their data to Sidekick.

We're not 100% sure this will be possible yet, as Sidekick is not fully defined. We know it would rely on there being an API (https://github.com/pa11y/sidekick/issues/22).

Hopefully this feature would really ease the switch-over, and help us deprecate Pa11y Dashboard faster.

**Comment by josebolos** [comment]
We're deprecating sidekick, so I'm closing this issue.
