### ISSUE TITLE
Ability to test an exclusive part of the page or widget

### ISSUE THREAD

**Issue by Rayraegah** [pa11y/pa11y-dashboard#139]
pa11y's feature

```
pa11y({
    hideElements: '.advert, #modal, div[aria-role=presentation]'
});

```

lets you hide specific elements on screen. This is useful when testing a page that has ads.

But is there a feature that lets a person test a specific branch/node of the DOM tree? example

```
pa11y({
    exclusiveTest: '.advert'
});
```

which will scan everything inside .advert. And can this be configurable option on the dashboard?

I'll provide a PR if this sounds like a nice to have feature - otherwise I might just keep it in my fork. web service and pa11y updates might be required :)

Here's what I do right now

Example using http://www.barclays.co.uk/PersonalBanking/P1242557947640

Bookmarklet for production testing
`javascript:(function(){$('.brand-logo').siblings().hide();$('.brand-logo').parents().siblings().hide();})();`

In test environment I have a test controller injected into every page that can do the above required feature using url parameters.

http://www.barclays.co.uk/PersonalBanking/P1242557947640?q=.brand-logo#pa11yVisible

**Comment by rowanmanning** [comment]
Hey @Rayraegah, the [`rootElement` option](https://github.com/pa11y/pa11y#rootelement-element) might be what you're looking for. Neither the `rootElement` or `hideElements` options are available in the dashboard as far as I know.

**Comment by Rayraegah** [comment]
@rowanmanning Yes! that's what I need.
