### ISSUE TITLE
EADDRNOTAVAIL

### ISSUE THREAD

**Issue by SA21** [pa11y/pa11y-dashboard#145]
Eeek! 500 error. This is serious.
There isn't much you can do about this.
Give it another go or try the home page.

Stack-Trace
Error: connect EADDRNOTAVAIL 0.0.0.0:4000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1062:14)

Windows 7

Running in development mode;PORT 8080;
Webservice PORT=4000
Mongo DB successfully connected.

Steps followed:
set NODE_ENV; 
set ports via development.json in config folder; 
C:>node index.js

started successfully,when tested in browser throws "EADDRNOTAVAIL" ERROR

**Comment by rowanmanning** [comment]
Hi @SA21, are you still having this issue? I can try to get access to a Windows machine and test it

**Comment by frvge** [comment]
I just ran into this on Windows 10. Changing the webservice host from 0.0.0.0 to 127.0.0.1 in, for example, config/test.json helped me.

```
$ NODE_ENV=test node index.js

Pa11y Dashboard started
mode: test
uri:  http://:::4000

Pa11y Webservice started
mode: test
uri:  http://0.0.0.0:3000

Error: connect EADDRNOTAVAIL 0.0.0.0:3000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)

Gracefully shutting down from SIGINT (Ctrl-C)

$ NODE_ENV=test node index.js

Pa11y Dashboard started
mode: test
uri:  http://:::4000

Pa11y Webservice started
mode: test
uri:  http://127.0.0.1:3000
```

**Comment by SA21** [comment]
great!!! it works for me now..Thanks alot @frvge

**Comment by prabhuignoto** [comment]
thanks @frvge that solved the problem for me.
