### ISSUE TITLE
The "eek! 500 error"  message is pretty unhelpful

### ISSUE THREAD

**Issue by hollsk** [pa11y/pa11y-dashboard#147]
"There isn't much you can do about this" is a defeatist attitude :p 

Let's update the 500 page so that it: 
- links to the new troubleshooting document;
- reminds users that they need to have the webservice and mongodb installed, and mongo running on the machine for it to work;
- "if all else fails, open an issue"

**Comment by rowanmanning** [comment]
I agree, error reporting is pretty bad at the moment. We should also ideally log the actual error that's occurring if we don't already.
