### ISSUE TITLE
Phantom Error Preventing Pa11y From Running

### ISSUE THREAD

**Issue by angelariggs** [pa11y/pa11y-dashboard#156]
* npm version: 3.10.8
* node version: v4.1.0
* mongodb version: 3.2.10 (installed through Homebrew)
* phantomjs version: stable 2.1.1 (installed through Homebrew)
* Mac OS X: Yosemite 10.10.5

Steps to reproduce:
* I forked and cloned the repo
* Ran `npm install`
* Ran `brew install phantomjs` and `brew install mongodb
* Copied the config files specified in the README
* `brew services start mongodb`
* `NODE_ENV=development node index.js`
* Added URL
* Clicked 'Run pa11y' on my URL
Received error message
```
Starting to run one-off task @ Mon Nov 07 2016 15:06:39 GMT-0800 (PST)
Starting task 581a5b8cb1c447a039a56c9a
Failed to finish task 581a5b8cb1c447a039a56c9a: Phantom immediately exited with: 127
Finished running one-off task @ Mon Nov 07 2016 15:06:39 GMT-0800 (PST)
```
This is preventing me from using Pa11y at all.

**Comment by rowanmanning** [comment]
Hi @angelariggs :) we had a similar issue in Pa11y itself a while back. There are a couple of things we can try:
1. Try following the solution in https://github.com/pa11y/pa11y/issues/175 – I'm not convinced that this is the same issue you're having but it's worth a try
2. Can you run `phantomjs -v`? Some people seem to have this issue if dependencies are missing

If neither of these work, I'll try replicating on my machine

**Comment by angelariggs** [comment]
@rowanmanning That seems to have solved it - thank you! :)

**Comment by rowanmanning** [comment]
Great! Let us know if you have any other issues :)
