### ISSUE TITLE
Minified JS is committed to the repo

### ISSUE THREAD

**Issue by hollsk** [pa11y/pa11y-dashboard#158]
From @frvge in PR #153 

> I'm not sure it's a good thing to include the minified version of the JS in the repo because now I had to commit that too. I propose that uglify runs after the npm install to generate it.

I think that's reasonable. @rowanmanning what do you think? Is there a reason for committing the processed JS that I don't know about?

**Comment by rowanmanning** [comment]
The only reasoning I think was to make installation simpler for people. We _could_ have the CSS/JS compiled the first time you start the application. Then in development mode it could recompile every time you change one of the source files.

**Comment by rowanmanning** [comment]
Considering that we're building Sidekick, I think we should close this issue – it'd be extremely time-consuming to change for little benefit
