### ISSUE TITLE
Out of memory randomly killing Dashboard

### ISSUE THREAD

**Issue by josebolos** [pa11y/pa11y-dashboard#160]
As discussed with @hollsk some time ago.

There seems to be a memory leak in phantomjs that may be causing Out Of Memory errors. On servers with a limited amount of memory this seems to be causing the OOM-killer to randomly kill the dashboard, leaving us without service.

We should have a look at implementing preventive measures (probably in webservice) in order to avoid this.

**Comment by hollsk** [comment]
I'm tentatively closing this issue because phantomjs is no longer in development, and there's an open PR in pa11y-webservice for getting Pa11y 5 into dashboard ( https://github.com/pa11y/pa11y-webservice/pull/58 ) and IMO that should take priority
