### ISSUE TITLE
No results in dashboard

### ISSUE THREAD

**Issue by girod** [pa11y/pa11y-dashboard#169]
Hi,

I use Mongodb version v3.4.1, node v6.9.4 and pa11y v4.3.0
I can create new tasks (I see task in mongo) in dashboard but I can't have any results when I launch tasks. I have no logs ..
Is there a known compatibilty problem ? Or how can I have log with pa11y ?

When I run on command line pa11y on specific url, service is ok. I have results.

Thks,

Franck

**Comment by hollsk** [comment]
Hi Franck - sorry you're having problems :-( 

I can't replicate your issue when I use those versions, so it's not a compatibility problem that we've come across, at least. What's your operating system?  

When you run the dashboard with `NODE_ENV=development node index.js` (or whichever env you're using), do you get console output when you launch a task? e.g. something like 

```
Starting to run one-off task @ Tue Jan 10 2017 12:28:44 GMT+0000 (GMT)
Starting task 5874d360bc15ab5c3875723d
```

**Comment by girod** [comment]
Thks for your answer.

When I run in development mode, here is the log :

Pa11y Dashboard started
mode: development
uri:  http://:::4000

Pa11y Webservice started
mode: development
uri:  http://0.0.0.0:3000

Starting to run one-off task @ Tue Jan 10 2017 17:12:56 GMT+0100 (CET)
Starting task 5875074aba55497b383cc7a3
**Failed to finish task 5875074aba55497b383cc7a3: PhantomJS binary was not found in PATH**
Finished running one-off task @ Tue Jan 10 2017 17:12:56 GMT+0100 (CET)

**Comment by hollsk** [comment]
Oh, excellent - that gives us some useful information. Maybe PhantomJS was incorrectly or partially installed. 

Could you please try deleting your `dashboard\node_modules` directory and running `npm install` again?
