### ISSUE TITLE
Add list of ignore rules to task page

### ISSUE THREAD

**Issue by perryharlock** [pa11y/pa11y-dashboard#17]
As a user
When on the task page
Then I want to be able to see the list of ignored rules for this url

**Comment by rowanmanning** [comment]
@perryharlock you can see the codes already:

``` html
<ul>
    {{#task.ignore}}
        <li>{{.}}</li>
    {{/task.ignore}}
</ul>
```

**Comment by perryharlock** [comment]
Do we not have the detail for the ignore rules? Is it just the code? @rowanmanning
