### ISSUE TITLE
Is anyway to run audit for multiple pages?

### ISSUE THREAD

**Issue by FJLopezGarcia** [pa11y/pa11y-dashboard#175]
Hi Team,

Congrats for this fantastic project!! 
Is any way to run audit for multiple pages at the same time, i mean adding more than 1 URL and run the execution? or is just per page?

Thanks!

**Comment by hollsk** [comment]
Hi @FJLopezGarcia - glad you like the project!

Right now we only support one URL per report in the Dashboard, but we have some ideas for grouping URLs in reports that we're planning to integrate with Dashboard version 2 ([Sidekick](https://github.com/pa11y/sidekick)). 

V2 is in alpha right now, but you can watch that repo for updates if you're keen 😄

**Comment by rowanmanning** [comment]
I'm going to close this issue as the work will not be done in Dashboard. Looks like it'll definitely make it into Sidekick though.

**Comment by kapiloliveti-fusion** [comment]
Hi guys just wanted to check when the Dashboard version2 will be ready for running the multiple urls at one go
