### ISSUE TITLE
Edit tasks - I am receiving an Oh my gosh! Error: "actions" is not allowed

### ISSUE THREAD

**Issue by FJLopezGarcia** [pa11y/pa11y-dashboard#177]
Hi all,
I am receiving and "Error: "actions" is not allowed" trying to update a HTTP Header value (same for other fields). Is this an issue? Users cannot edit and save values from existing tasks?

**Comment by rowanmanning** [comment]
Hey @FJLopezGarcia, did you update the dashboard recently? You probably need to reinstall dependencies – actions were added to the dashboard recently and they depend on an updated webservice. Could you try running:

```sh
npm install
```

**Comment by FJLopezGarcia** [comment]
Hi @rowanmanning, thanks a lot for your quick response!!

I have run `'npm install` after deleting my "node_modules" folder to start from scratch. Also I created again my mongo database... but now i am receiving a **Oh my gosh! Error: child "actions" fails because ["actions" must be an array]** when i didn't include any action in my task.

**Comment by rowanmanning** [comment]
OK I'll jump in and investigate, thanks for reporting

**Comment by rowanmanning** [comment]
I can replicate locally, just patching. Will let you know when a new release is out :)

**Comment by rowanmanning** [comment]
Hey @FJLopezGarcia, I've just released version 2.2.1 which should fix this issue. Could you update and test it for me?

**Comment by FJLopezGarcia** [comment]
Hi @rowanmanning the fix works. You can close the bug!! thanks.
