### ISSUE TITLE
Functionality to download results as CSV or JSON

### ISSUE THREAD

**Issue by perryharlock** [pa11y/pa11y-dashboard#18]
As a user
When on the tasks page
Then I should be able to download the results for the selected date as a CSV or JSON file.

**Comment by rowanmanning** [comment]
I reckon you could have a go at this, at least the JSON one anyway. Let's pair on it

**Comment by perryharlock** [comment]
Ok, so the download.json button will now open a tab with the json for that task / url shwoing the numbers. This needs to be changed so that it opens the results for the date we are viewing....when that functionality is available ;-)

**Comment by rowanmanning** [comment]
This is done. Work OK for you, @perryharlock?

**Comment by perryharlock** [comment]
Yep works great :-) I'll close it for you
