### ISSUE TITLE
Unable to connect to pa11y-webservice

### ISSUE THREAD

**Issue by syndy1989** [pa11y/pa11y-dashboard#182]
Hi 
 Am I missing something here?
I have installed pa11y and it runs just fine from command line
Checked config files
npm install done
mongodb is running

node v6.10.0
mongodb,3.4
phantomJS
pa11y-dashboard 2.2.1

When I start the service (ie: node index.js)

I get shown

pa11y-dashboard started

mode: production
uri: http://:::4000

pa11y-webservice started

mode:production
uri: http://127.0.0.1:27017

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)

but if I browse to the uri, I get 500 error

Eeek! 500 error.
Let's see what we can do here:
Do you have MongoDB installed and mongod running?
Check out the Troubleshooting doc for more information.
Search for a related Github issue, or open one yourself.
Stack-Trace
Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)

what am i doing wrong? Any advise would be helpful. Thanks in advance.

**Comment by hollsk** [comment]
Hi @syndy1989 - thanks for using Pa11y! Please could you tell us your operating system and also show us your config files? `ECONNRESET` is a very general network error with a huge range of potential causes. Some more details might help us narrow it down.
