### ISSUE TITLE
Pa11y-crawl is not working

### ISSUE THREAD

**Issue by syndy1989** [pa11y/pa11y-dashboard#183]
I'm using cygwin on windows system. 

i successfully downloaded python, phantomjs, jq, npm, nodejs
I'm getting response for pa11y-crawl

$ pa11y-crawl
Usage: pa11y-crawl [options] <URL>

Options:
  -d, --directory       use an existing local directory instead of wget
  -c, --continua11y     set continua11y URL (default: continua11y.18f.gov)
  -f, --filter          filter the scan to specified files
  -h, --help            show this help message and exit
  -i, --ci              continuous integration mode; incorporates repo metadata
                          and sends a report to continua11y
  -m, --sitemap         use the site's sitemap.xml to find pages, rather than wget spider
  -o, --output          set output file for report (default: ./results.json)
  -p, --parallel        the number of parallel processes to run (default: 1)
  -q, --quiet           quiet mode
  -r, --run             pass a command to start a local server for analysis
  -s, --standard        set accessibility standard
                          (Section508, WCAG2A, WCAG2AA (default), WCAG2AAA)
  -t, --temp-dir        set location for storing temporary files (default: ./temp)
  -w, --wait            set waiting time for app startup, in seconds (default: 5)
  -v, --version         show program version and exit

but when i try  $pa11y-crawl nature.com

I get shown the below error

$ pa11y-crawl --ci nature.com
 >>>  running on unknown ci; building information
 >>>  using wget to mirror site
 <<<  found 1 files in 1 directories
 >>>  beginning the analysis
 |---------------------------------------
C:\Users\AppData\Roaming\npm/node_modules/pa11y-crawl/pa11y-crawl.sh: line 58: python: command not found
 ||    is not an html document, skipping
C:\Users\AppData\Roaming\npm/node_modules/pa11y-crawl/pa11y-crawl.sh: line 58: python: command not found
 ||    is not an html document, skipping
C:\Users\AppData\Roaming\npm/node_modules/pa11y-crawl/pa11y-crawl.sh: line 58: python: command not found
 |---------------------------------------
 |->  analyzing
C:\Users\AppData\Roaming\npm/node_modules/pa11y-crawl/pa11y-crawl.sh: line 266:  9192 Segmentation fault
-s '.[0] * {data: {(.[1].url): .[1]}}' $OUTPUT $TEMP_DIR/pa11y.json > $TEMP_DIR/temp.json
parse error: Invalid numeric literal at line 2, column 8
parse error: Invalid numeric literal at line 2, column 8
parse error: Invalid numeric literal at line 2, column 8
 <<<  pa11y says: error:  | warning:  | notice:
 >>>  sending data to continua11y
C:\Users\AppData\Roaming\npm/node_modules/pa11y-crawl/pa11y-crawl.sh: line 316: curl: command not found
 >>>  cleaning up

Am i doing anything wrong. Anyadvise would be helpful. Thanks in advance

**Comment by rowanmanning** [comment]
Hi @syndy1989: `pa11y-crawl` isn't something we maintain, so I'm not sure what's wrong here. It seems to have been moved to https://github.com/18F/continua11y – I'd ask for help there :)

**Comment by syndy1989** [comment]
@rowanmanning 
Ok Thank You
