### ISSUE TITLE
os.tmpDir() is deprecated. Use os.tmpdir() instead.

### ISSUE THREAD

**Issue by lasithds** [pa11y/pa11y-dashboard#194]
```
NODE_ENV=test node index.js

Pa11y Dashboard started
mode: test
uri:  http://:::4000
(node:7857) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

Pa11y Webservice started
mode: test
uri:  http://0.0.0.0:3000

```

When loading the page it shows this
`{"statusCode":404,"error":"Not Found"}`

Am I doing something wrong?

**Comment by lasithds** [comment]
Sorry it was just a warning. I was trying to load the Webservice instead of the dashboard. Dashboard   loads without any problem.

**Comment by Mystina** [comment]
I met the same issue. Can I ask how you load the dashboard? @lasithds
