### ISSUE TITLE
Errors grouping problem

### ISSUE THREAD

**Issue by emusatova** [pa11y/pa11y-dashboard#195]
### Hello Team

During the working process, our team found the next problem.
When there are errors from the one guideline (like from the example below), the tool groups them, and shows only the first DOM element selector. And there is no way how to find other elements with the same problem.
This also causes a misunderstanding when you try to fix the problem, and watch for 39 same selectors, but can find only one and really don't know why the amount of errors is so big.

We tested the desktop version of dashboard (Koa11y), and there is no such problem. It generates reports with the information for every rule and element.

So, the possible solutions:
* not to group the errors (1 element – 1 error) 
* show all problematic elements' selectors inside the error block

#### Example
![screen shot 2017-10-03 at 4 56 14 pm](https://user-images.githubusercontent.com/2951424/31131899-b97d5234-a85b-11e7-85cb-5dc7ec774c6b.png)

Thank you in advance.

**Comment by rowanmanning** [comment]
Hi @emusatova, yeah I can see how this would be an issue for you. Possibly we could look at adding in the ability to see all of the selectors and contexts within a dropdown. I'll speak with the team about it.

Equally if you have time to investigate further whether this is possible then let me know :)

**Comment by emusatova** [comment]
Hi @rowanmanning ,

Yes, I've already implemented this functionality for our team needs :) 
And now I'm going to make its design better, and discuss with team the possibility of sending pull request to you.

**Comment by emusatova** [comment]
The issue was fixed.
