### ISSUE TITLE
[Question] Does pa11y cli populate the dashboard?

### ISSUE THREAD

**Issue by jasonday** [pa11y/pa11y-dashboard#199]
If I set up scans against a url with a set of actions and other config, can I have those results populate the pa11y dashboard?

**Comment by rowanmanning** [comment]
Hi Jason, so you mean:

  - run the Pa11y command-line client on a URL
  - results from that run appear in the dashboard

The answer is no, and it's unlikely to happen for now at least. This would be totally possible by building a custom Pa11y reporter though and pushing results into the dashboard via [Pa11y Webservice](https://github.com/pa11y/pa11y-webservice) (which is included in dashboard).
