### ISSUE TITLE
View diffs between results

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y-dashboard#2]
Add the ability to view diffs between results, so you can easily see which errors are new or which errors have been fixed.

**Comment by adelevie** [comment]
This feature would be great. How do you think you could uniquely identify results?

**Comment by rowanmanning** [comment]
Right now, I'm not 100% sure. I think I'd probably need to overhaul the way results are stored. This probably wouldn't make it in before a larger rewrite.

**Comment by rowanmanning** [comment]
This feature's unlikely to make it into Pa11y Dashboard, it'd require quite a bit of work on Pa11y Webservice. Both of these projects are ramping down heavy feature work in favour of Pa11y Sidekick.

The good news: [Pa11y Sidekick will hopefully have this feature from the start](https://github.com/pa11y/sidekick/issues/13) – I'm really enthused about it, and I think it'd make the whole thing _way_ more useful.
