### ISSUE TITLE
Nothing happens when I hit RunPa11y

### ISSUE THREAD

**Issue by Jhinjer** [pa11y/pa11y-dashboard#200]
Hi All,

Any help on this will be much appreciated.

I have installed Pa11y dashboard, it's up and running, but when I add my local urls to test accessibility and hit RUN, nothing happens.

Any one faced same issue, please help.

Thanks

**Comment by Jhinjer** [comment]
Sorted this out :)

**Comment by Mystina** [comment]
@Jhinjer hey how did you figure this out? I have the same problem.
