### ISSUE TITLE
Pa11y dashboard with headless chrome

### ISSUE THREAD

**Issue by Jhinjer** [pa11y/pa11y-dashboard#201]
Can we run the dashboard with Pa11y@beta.. ?

**Comment by rowanmanning** [comment]
Currently no, and I'm not sure the dashboard ever will run Pa11y 5.x as we're ramping down feature development in favour of working on [Sidekick](https://github.com/pa11y/sidekick). Is there anything in particular in the beta that you feel is missing from the dashboard, aside from using Chrome?

**Comment by Jhinjer** [comment]
Hi Rowan,
Yeah, it works perfectly fine with phantomjs but once we change
configuration for Chrome it stops working, any particular files where we
need to make changes?
Thanks
Sumanpreet Singh Jhinjer

On 23 Nov 2017 8:51 pm, "Rowan Manning" <notifications@github.com> wrote:

Currently no, and I'm not sure the dashboard ever will run Pa11y 5.x as
we're ramping down feature development in favour of working on Sidekick
<https://github.com/pa11y/sidekick>. Is there anything in particular in the
beta that you feel is missing from the dashboard, aside from using Chrome?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pa11y/pa11y-dashboard/issues/201#issuecomment-346572445>,
or mute the thread

**Comment by rowanmanning** [comment]
Pa11y Dashboard doesn't support Headless Chrome at all, so if you're configuring it to use Headless Chrome then yeah it just won't work. Am I misunderstanding what you're trying to do?

**Comment by Jhinjer** [comment]
Yeah, you are absolutely to the point. We were trying to make Pa11y beta
headless Chrome to work in Pa11y dashboard. Which now seems impossible.
