### ISSUE TITLE
README screen grabs are out of date

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y-dashboard#202]
There have been quite a few visual updates since these screen grabs were taken. We should probably update them!

**Comment by shrej** [comment]
@rowanmanning 

I just discovered this project. This is awesome. 👍  

I will take this task. I"ll have a PR shortly.

**Comment by peacedude95** [comment]
Is anyone still working on this? If not I'll take it

**Comment by hollsk** [comment]
still available, all yours!

**Comment by hollsk** [comment]
@peacedude95 it's all yours if you still want it!

**Comment by josebolos** [comment]
Fixed in #237, #239.
