### ISSUE TITLE
Error executing command to extract phantom ports

### ISSUE THREAD

**Issue by MrMMorris** [pa11y/pa11y-dashboard#204]
I am trying to run the dashboard in docker and I get this error when trying to scan a url:

```
Failed to finish task 5a980a6f45bb2c010080cc96: Error executing command to extract phantom ports: Error: Command failed: ss -nlp | grep "[,=]15," || netstat -nlp | grep "[[:space:]]15/"
/bin/sh: 1: netstat: not found
```

So I install `net-tools`. Now this is the error:

```
Failed to finish task 5a980a6f45bb2c010080cc96: Error executing command to extract phantom ports: Error: Command failed: ss -nlp | grep "[,=]92," || netstat -nlp | grep "[[:space:]]92/"
```

The **Dockerfile** is very straightforward:

```
FROM  node:4-onbuild
RUN npm install --production
RUN npm install --global phantomjs-prebuilt
EXPOSE 3000
EXPOSE 4000
CMD ["node", "index.js"]
```

I have seen this issue here: https://github.com/pa11y/pa11y/issues/103 and https://github.com/baudehlo/node-phantom-simple/issues/76, but have not been able to find a solution. Any ideas?

**Versions:**
```
Mongo 3.2
Phantom 2.1.1
Node 4.8.7
```

**Comment by rowanmanning** [comment]
Hi @MrMMorris, apologies for the long wait on a reply. Are you still having this issue? If so I can try to replicate and get this fixed

**Comment by MrMMorris** [comment]
I was actually able to figure it out just now. I was attempting to run pa11y with just pure docker outside of compose which is where the issue comes from. The output from the `ss` command is different for docker vs compose because of how the networking it set up in compose. The differences in output are below. 

**Lesson: Do not run outside of docker-compose** 

`ss` output with `docker`:
```
Netid State      Recv-Q Send-Q                       Local Address:Port                         Peer Address:Port
tcp   LISTEN     0      128                                      *:3000                                    *:*
tcp   LISTEN     0      128                                     :::4000  
```

`ss` output with `docker-compose`:
```
Netid State      Recv-Q Send-Q                       Local Address:Port                         Peer Address:Port
tcp    LISTEN     0      128                         127.0.0.1:3000                          *:*      users:(("node",pid=1,fd=13))
tcp    LISTEN     0      128                         :::4000                                :::*      users:(("node",pid=1,fd=10))
```
