### ISSUE TITLE
Broken README link/anchor

### ISSUE THREAD

**Issue by aroseartist** [pa11y/pa11y-dashboard#205]
README link is broken for dev instructions link/anchor:

"See development instructions for more information..."
should go to: https://github.com/pa11y/pa11y#development

Anchor does not exist. Where or what information should this point towards?

**Comment by hollsk** [comment]
Good catch! We renamed the "Development" section to "Contributing" but forgot to update the anchor 🤦‍♀️ 

Would you like to do the honours with a PR for us? 😄
