### ISSUE TITLE
Pa11y dashboard no results.

### ISSUE THREAD

**Issue by dkay703** [pa11y/pa11y-dashboard#207]
Node version 6.14.1 
Mongodb version 3.6.3
Dashboard version 2.4.1

when i run ./pa11y url in command line, it returns expected results. However, in dashboard, no results are returned after running pa11y against a url.

I don't see any logs or troubleshoot guide that I can reference to.

Do you have any suggestion to resolve this issue?

Thanks,

**Comment by amitcsknit** [comment]
No results in dashboard appearing for  me also. are you able to find ant resolution @dkay703
