### ISSUE TITLE
Add delete button to tasks on home page

### ISSUE THREAD

**Issue by perryharlock** [pa11y/pa11y-dashboard#21]
Add delete buttons with the href of /{{id}}/delete to the tasks on the home page
@rowanmanning to complete functionality

**Comment by perryharlock** [comment]
Delete buttons added - @rowanmanning we need the delete page so reassigning to you.
If you re-assign it back to me when the page and functionality is there I can style it up.
I assume we will need a confirmation alert to say that it has been deleted...or something. Balloons, bunting maybe even a cake.

**Comment by rowanmanning** [comment]
Is this almost the same as 16? I think we should combine the issues.

**Comment by perryharlock** [comment]
Yep looks like it

**Comment by rowanmanning** [comment]
Functionality has been added. Delete page needs some design love though :) (23ffae54fa7a1c96245bf93e51d247be7c746e01)
