### ISSUE TITLE
Pa11y dashboard indicating error for action: navigate to

### ISSUE THREAD

**Issue by kevngan** [pa11y/pa11y-dashboard#212]
I am getting error while editing the action to navigate to another page.

Error: Invalid action: "navigate to

**Comment by hollsk** [comment]
Hi @kevngan - thanks for using Pa11y!

Could you please show us the entire error message, and also your config? 

Thank you 🙂

**Comment by hollsk** [comment]
Closing this one as there hasn't been a response for a while - if there's still a problem then feel free to open a new one!
