### ISSUE TITLE
screen capture action is Invalid action

### ISSUE THREAD

**Issue by peacedude95** [pa11y/pa11y-dashboard#213]
entered the action: 'screen capture example.png' on a task in the pa11y Dashboard. 
The below error message is displayed:
![image](https://user-images.githubusercontent.com/13383965/42085671-052422ca-7b89-11e8-87c9-df97f22ce9cf.png)

I have tried to validate using the `pa11y.isValidAction('action')` function, which returns true. In addition to this I attempted to run the same action in  in Pa11y, where a screen capture occurs successfully.

Let me know If you need any further details :)

**Comment by hollsk** [comment]
Hi @peacedude95! Thanks for your patience, everyone is on holiday right now ☀️

We'll be able to help soon - are you running the latest version of Dashboard?

**Comment by peacedude95** [comment]
@hollsk I am running version 2.4.2, yes

**Comment by hollsk** [comment]
Thank you!  I've dug around a little. 

Screen capturing was added in Pa11y 5. Dashboard uses Pa11y 4, so it's not available there, as you've found. 

I can try to backport screen capturing into Pa11y 4 for you, but almost everyone is away right now, so it might be a little while before I can get a PR merged.

**Comment by hollsk** [comment]
Status update: I've backported this functionality, but I need help with the test suite before I can merge and release. See the PR if you'd like to help 👍 https://github.com/pa11y/pa11y/pull/414

**Comment by hollsk** [comment]
Closing this now as we've just updated Dashboard to use Pa11y 5, so the backport isn't needed anymore, and screen capture is available in Dashboard as expected 😄 

https://github.com/pa11y/pa11y-dashboard/blob/master/CHANGELOG.md
