### ISSUE TITLE
Hosted instances available?

### ISSUE THREAD

**Issue by jywarren** [pa11y/pa11y-dashboard#214]
Hello, I work at @publiclab, a non-profit doing community environmental work. Does anyone offer hosted pa11y instances? 

Does anyone have pa11y hooked up as a GitHub hook so it appears as a "check" on GitHub pull requests, like in this screenshot?

![image](https://user-images.githubusercontent.com/24359/43913116-2c265fe6-9bd2-11e8-86e7-65d7c82d59e9.png)

(https://github.com/publiclab/leaflet-blurred-location/pull/151)

Thank you!!

**Comment by jywarren** [comment]
Ooh, ok, i see this: https://una.im/pa11y-dash/

Opening our own issue then. Thanks! https://github.com/publiclab/plots2/issues/3223

**Comment by hollsk** [comment]
Glad you got it sorted 😄
