### ISSUE TITLE
Results shown on the dashboard are not the same as the HTML Snippet

### ISSUE THREAD

**Issue by HectorPersonalGit** [pa11y/pa11y-dashboard#219]
I used pa11y dashboard to test a local page, the results are completely different from the HTML Snippet.

Dashboard: 1 error, 1 warning, 2 notices
HTML Snippet: 33 errors, 28 warnings, 277 notices.

The difference is significant enough to make me suspicious something is going on. 

The site I'm testing is served via webpack, built using ReactJS, running on my Localhost

**Comment by josebolos** [comment]
Hi @madebyhector,

Thanks for creating the issue. We wrote about this a while ago in our troubleshooting guide: https://github.com/pa11y/pa11y/blob/master/TROUBLESHOOTING.md#why-does-pa11y-give-different-results-to-the-html-codesniffer-bookmarklet

> If parts of the DOM are been loaded after the document is first generated, you may get results that differ from the bookmarklet which runs in the browser and can test against the complete DOM.

You mention that you are using React. Do you think this could this be the case, and content is being loaded after pa11y runs?

The [screen capture action](https://github.com/pa11y/pa11y#screen-capture) may help you confirm if this is indeed the case.

**Comment by HectorPersonalGit** [comment]
I tried setting timers and target rules to launch pally but nothing worked.

---
Hector Rodriguez
hector.rodriguez@gmail.com


________________________________

**Comment by josebolos** [comment]
Hi @HecOsbRod,

Are you still experiencing this issue?

**Comment by josebolos** [comment]
Thanks for creating this issue. It looks like this may be fixed now, feel free to reopen the issue if not.
