### ISSUE TITLE
Results don't match HTML Code Sniffer via browser snippet

### ISSUE THREAD

**Issue by walter-schuh** [pa11y/pa11y-dashboard#224]
The result given via pa11y dashboard do not currently match the results given by the current version of the HTML Code Sniffer snippet.  I had a quick look at this and it looks like there is an updated version of the underlying pa11y library dependency available (that references this newer version of the Code Sniffer) that has not been pulled through to the current version of pa11y dashboard.

**Comment by josebolos** [comment]
Hi @walter-schuh,

Thanks for creating the issue. It's true that we're not using the latest version of HTML_CodeSniffer. That said, there's a number of reasons why the results may differ, specially for sites that render content client-side.

We wrote about this a while ago in our troubleshooting guide: https://github.com/pa11y/pa11y/blob/master/TROUBLESHOOTING.md#why-does-pa11y-give-different-results-to-the-html-codesniffer-bookmarklet

> If parts of the DOM are been loaded after the document is first generated, you may get results that differ from the bookmarklet which runs in the browser and can test against the complete DOM.

Do you think there's any chance this could be what is happening? Unfortunately you didn't provide a site we can test.
