### ISSUE TITLE
Failed to finish task in pa11y Dashboard

### ISSUE THREAD

**Issue by amitcsknit** [pa11y/pa11y-dashboard#227]
when i run any task fron dashboard of pa11y it does not run and in backend inside ubuntu 16.04 it giving error as PhantomJS browser exited & ailed to finish task

 phantomjs -v 1.9.8
pa11y -V 5.1.0
npm: '6.4.1'
/usr/local/bin/phantomjs -v 1.9.8

===========Full trace below===================

Starting to run one-off task @ Tue Mar 05 2019 13:51:59 GMT-0600 (CST)
Starting task 5c7ecc43bda012e482351a08
  > PhantomJS browser exited
Failed to finish task 5c7ecc43bda012e482351a08: Request() error evaluating createPage() call: Error: connect ECONNREFUSED ::1:44798
Finished running one-off task @ Tue Mar 05 2019 13:51:59 GMT-0600 (CST)

**Comment by josebolos** [comment]
Hi @amitcsknit, 

We've released [version 3 of pa11y dashboard](https://github.com/pa11y/pa11y-dashboard/blob/master/CHANGELOG.md#300-2019-07-16), which replaces Phantomjs with Headless Chrome. Would you mind trying the new version and letting us know if you're still experiencing this issue, please? Thanks!
