### ISSUE TITLE
hosting pa11y dashboard

### ISSUE THREAD

**Issue by petervangennip** [pa11y/pa11y-dashboard#230]
I want to deploy the pa11y dashboard to a live environment (azure) so we can have the dashboard on multiple screens around the office. 

Is this possible?

**Comment by josebolos** [comment]
Hi @pwavg,

I'm not familiar with Azure, but we use CloudFoundry at Springer Nature and pa11y dashboard works just fine with it, so I wouldn't expect you to have any problems with it.

Let us know if you have any questions!

**Comment by petervangennip** [comment]
Hi @josebolos , 

Did you do any custom configuration? And do you still need to run MongoDB? Sorry, don't have a lot of knowledge of this sort of thing.

**Comment by josebolos** [comment]
No custom configuration needed in our case, and yes, you still need to run MongoDB as that's where the results are stored. In our case the DB is provisioned on a separate server, so pa11y-dashboard can be redeployed easily without any loss of data.
