### ISSUE TITLE
Ability to crawl entire sites

### ISSUE THREAD

**Issue by sandysh** [pa11y/pa11y-dashboard#232]
Hello Pa11y team,
I was wondering if there is a way to crawl entire website. I mean instead of adding a single url, crawl though all the links of a given website and run pa11y for results. Is that possible ? please enlighten me if so.

Thank you.

**Comment by hollsk** [comment]
Hi @sandysh - there's no way to do this in Pa11y itself, but the 18F team wrote a separate Pa11y crawler: https://github.com/18F/pa11y-crawl (they're not actively maintaining it, though)

If you're using continuous integration, we also have [Pa11y CI](https://github.com/pa11y/pa11y-ci), which accepts an XML sitemap. 

An alternative would be to use something like https://github.com/liip/TheA11yMachine
