### ISSUE TITLE
404 error on «run» action on task

### ISSUE THREAD

**Issue by tassoman** [pa11y/pa11y-dashboard#241]
Hello there,
 I just cloned **pa11y-dashboard** repository master branch then followed install instructions to get the latest version (3.0.0).

Web gui is working and data is pulled from the MongoDB database was set in the old installation.
I’m able to create and delete tasks but when it's done, `/{taskid}/run` **GET action is not possible** because 404 error is thrown. (I get also GET a 404 error on /{taskid}/favicon.ico)

This happens to new created tasks and old tasks. 
Maybe the _Chromium puppeteer_ backend isn’t working as expected?
Any chance to debug logging in the console?

Thanks in advance!

**Comment by tassoman** [comment]
After posting this, I’ve found hints inside the console. Then I realized I was missing dependencies to run chrome (chromium). 
[This comment on Centos7](https://github.com/GoogleChrome/puppeteer/issues/391#issuecomment-398660894) was resolutive but now I’m in troubles with the sandbox.

**Comment by tassoman** [comment]
Getting the sandbox working in Centos7 is possible, doing like that in [this paragraphs](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/linux_suid_sandbox_development.md). The kernel is too much old.

Now I can complete some tasks but other tasks are dying because of javascript errors inside the tested pages. I've catched [some logging about this](https://gist.github.com/tassoman/6f4e92239ad62fda07bc4f5d1e0d5392).
The result is another 404 error on failed tasks.

**Comment by josebolos** [comment]
Hi @tassoman 

Thanks for creating this issue! We've just released version 3.0.1 of pa11y-dashboard which fixes an issue with tasks not being run by the cron job.

Would you mind giving it a try and see if that makes any difference to your problem?

Thanks!

**Comment by tassoman** [comment]
I’ve pulled this repository then restarted but nothing happened.
I thought I didn’t pulled any code but for real I got the updated `package.json`. 
I wasn’t aware because **pa11y-dashboard version wasn't bumped to 3.0.1**

By the way I read the commit so I decided to `npm update` pulling the _3.0.1 pa11y-webservice_ dependency.

Now cronjobs are back and working, for me the issue is fixed.
Some of my tasks stills failing but nothing is happening in the dashboard. Stats are «paused» at the last working day.

**Comment by josebolos** [comment]
Hi @tassoman,

Are you still experiencing this issue?

**Comment by tassoman** [comment]
I just pulled pa11y/dashboard master repository, then I've did `npm update`, finally I've started the project and I got version 3.1.0 running.
Issue has gone, I bet was solved by [#487](https://github.com/pa11y/pa11y/issues/487). Now it works, jobs are running. Thank you!
