### ISSUE TITLE
Ability to select run date from dropdown on the task page and see results for that date

### ISSUE THREAD

**Issue by perryharlock** [pa11y/pa11y-dashboard#25]
As a user
When I am on the task page
Then I need to be able to select a run date from the dropdown in the left column and be taken to the results for that date. The results should be reflected in the graph, the table for the graph, the main content of the right column and the task stats below the date selector.

**Comment by rowanmanning** [comment]
Did we decide to do with with a separate URL for each result set in the end?

**Comment by perryharlock** [comment]
Yes (perry)

**Comment by rowanmanning** [comment]
Part done in 00dbebc1a61a6b6fbdda5e3ff1185f9153863822.

**Comment by rowanmanning** [comment]
Should this be marked as done? I know there's no graph on the result page, but I reckon that's a new ticket

**Comment by perryharlock** [comment]
Spose this is done. You better set the other ticket up then eh? Eh? Eh?!!!!
