### ISSUE TITLE
Possible to use mongodb through deployd?

### ISSUE THREAD

**Issue by jasonday** [pa11y/pa11y-dashboard#251]
I have mongodb available through deployd (http://name.domain.com:8050)

I haven't been able to figure out the right combination to get this to work with the configuration:
```
{
	"port": 4000,
	"noindex": true,
	"readonly": false,

	"webservice": {
		"database": "mongodb://localhost/pa11y-webservice-dev",
		"host": "0.0.0.0",
		"port": 3000,
		"cron": "0 30 0 * * *"
	}
}
```

**Comment by josebolos** [comment]
Hi @jasonday!

Sorry I missed this issue. I'm not sure what deployd is, but as long as you use the correct mongodb connection string (e.g. `mongodb://myUsername:myPassword@name.domain.com:8050/`) and the database host and port are accessible to pa11y-dashboard, this shouldn't be a problem at all.
