### ISSUE TITLE
WCAG2.1 supporting

### ISSUE THREAD

**Issue by skudrua2019** [pa11y/pa11y-dashboard#255]
Hi!,
1. Do pa11y dashboard and other Pa11y products support and check checkpoints from WCAG2.1?
2. I saw the issue in the tracker about groping in the dashboard, would like to know whether this feature is going to be implemented and when?
Thanks.

**Comment by josebolos** [comment]
Hi @skudrua2019 

Thanks for creating this issue!

Regarding WCAG 2.1 support in pa11y-dashboard, it's something that it's definitely in the roadmap. It may take a long time though, as there's lots of changes to be made before that can happen. We've create a new issue for it: #263.

Regarding grouping of results, it's definitely something that we would like to have, but we don't have any specific plans to implement it at the moment. I would suggest to subscribe to #254 so you'll be notified if there are any developments in that area.
