### ISSUE TITLE
Unable to run Pa11y Dashboard in local - TypeError: tasks.map is not a function

### ISSUE THREAD

**Issue by selvakumarca** [pa11y/pa11y-dashboard#261]
Hi,
I have cloned the latest version of Pa11y dashboard (v3.1.0) in my machine. I was able to perform npm install and that went through without any errors. I was able to get mongod process running without any issues. When I run, NODE_ENV=development node index.js, I get this in the terminal console:

**Pa11y Dashboard started**
mode: development
uri:  http://:::4000
Server running at: http://0.0.0.0:3000

**Pa11y Webservice started**
mode:     development
uri:      http://0.0.0.0:3000
database: mongodb://localhost/pa11y-webservice
cron:     0 30 0 * * *

I am able to access the webservice at port 300 (http://localhost:3000/)
Pa11y-webservice is running. Documentation at https://github.com/pa11y/pa11y-webservice/wiki/Web-Service-Endpoints

But when I access the Pa11y dashboard app at port 4000 (http://localhost:4000/), I see the following error in the console

```
/Users/my-MBP/Practice Projects/pa11y-dashboard/route/index.js:29
				tasks: tasks.map(presentTask),
				             ^
TypeError: tasks.map is not a function
    at app.webservice.tasks.get (/Users/my-MBP/Practice Projects/pa11y-dashboard/route/index.js:29:18)
    at Request._callback (/Users/my-MBP/Practice Projects/pa11y-dashboard/node_modules/pa11y-webservice-client-node/lib/client.js:126:3)
    at Request.self.callback (/Users/my-MBP/Practice Projects/pa11y-dashboard/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/Users/my-MBP/Practice Projects/pa11y-dashboard/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/Users/my-MBP/Practice Projects/pa11y-dashboard/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pa11y-dashboard@3.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pa11y-dashboard@3.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/my-MBP/.npm/_logs/2020-06-08T14_37_57_450Z-debug.log
```

**Additional Info**:
OS: macOS Mojave (v10.14.6)
Node: v10.17
NPM: v6.11.3
Mongo: v4.2.7 (Community edition)

Any specific reason, why the dashboard URI is being shown as uri:  http://:::4000 in the terminal console?

**Comment by josebolos** [comment]
Hi @selvakumarca 

Thanks for the detailed bug report. Unfortunately, I can't seem to be able to replicate the error.

Would you be able to attach the config that you're using? Feel free to redact any sensitive data (hostnames, passwords, etc).

The http://:::4000 is a cosmetic error that should be fixed, as you have correctly guessed the URL will usually be http://localhost:4000.

**Comment by selvakumarca** [comment]
Hi @josebolos 

I'm just using the default development config. I renamed development.sample.json to development.json under config directory. Here's the config:

```
{
	"port": 4000,
	"noindex": true,
	"readonly": false,
	"webservice": {
		"database": "mongodb://localhost/pa11y-webservice-dev",
		"host": "0.0.0.0",
		"port": 3000,
		"cron": "0 30 0 * * *"
	}
}
```

I used **NODE_ENV=development node index.js** to run the app. I have removed my node modules and ran 'npm install' multiple times. Didn't make a difference.

**Comment by selvakumarca** [comment]
Figured out that this was a problem with my corporate proxy settings, which hindered the HTTP request from dashboard client app to web service. Adding a NO_PROXY to the proxy list solved the issue.
