### ISSUE TITLE
Update rulesets list to add WCAG 2.1 options

### ISSUE THREAD

**Issue by hollsk** [pa11y/pa11y-dashboard#263]
Jose says about Pa11y core:
>We released pa11y-6.0.0-alpha which has preliminary support for some of the new WCAG 2.1 rules
>It seems to be working fine as far as I can tell, but some work is still required in order to assign the rules to the appropriate set and allow people to select between WCAG 2.0/2.1 A/AA/AAA

Once that work has been released, we need to update Dashboard so we can make those selections here too.

**Comment by josebolos** [comment]
Fixed by #290.
