### ISSUE TITLE
Github front page for Dashboard claims our latest release was in 2015

### ISSUE THREAD

**Issue by hollsk** [pa11y/pa11y-dashboard#265]
<img width="316" alt="Screen Shot 2020-08-10 at 14 17 46" src="https://user-images.githubusercontent.com/1948361/89786771-60ea0600-db14-11ea-98b9-69ee61c7c410.png">

The Github [front page for Dashboard](https://github.com/pa11y/pa11y-dashboard) is _lying_. The latest release was in 2019. 

Something to do with how Github treats releases vs "releases" 🙄 We should try to fix it.

**Comment by maxleee** [comment]
Hi I think I could fix this. Just need to make releases to correspond to the tags. Would you want a release for each tag or just for the latest?

**Comment by sangitamane** [comment]
This should be fixed now. Adding release title makes it working. But the release date is showing today's which is wrong :(
