### ISSUE TITLE
Failed to launch chrome! in Docker Container

### ISSUE THREAD

**Issue by sagarmal624** [pa11y/pa11y-dashboard#266]
Pally Dashboard is running in Docker Container and when we run pally task then getting error 404. I checked Docker logs for this and found below Error. Can anyone please help me to resolve this. tried multiple things to fix it. ??? 

Starting task 5f46208ace99de1844fea979
[5f46208ace99de1844fea979]  > Running Pa11y on URL https://www.fwd.co.th/en/products/
[5f46208ace99de1844fea979]  > Launching Headless Chrome
model:task:runById failed, with id: 5f46208ace99de1844fea979
Failed to launch chrome! spawn ./node_modules/puppeteer/.local-chromium/win64-686378/chrome-win/chrome.exe ENOENT

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by anandsourabh** [comment]
I am facing the same issue and clueless how to resolve it. I deploying pa11y-dashboard in RHEL based docker container!

**Comment by tyjak** [comment]
You have to had in production.js : 
```
    "chromeLaunchConfig": {
       "args": ["--no-sandbox"]
    }
```

You can see a config file that works for me a here : https://github.com/RobLoach/docker-pa11y/pull/10/files#diff-7e9475eacc38f176f418927232de009e5d55a4d0a0398d939dcf4ad4afe55bd0

**Comment by josebolos** [comment]
Thanks for creating this issue. It looks like this may be fixed now, feel free to reopen the issue if not.
