### ISSUE TITLE
Basic authentication to view dashboard

### ISSUE THREAD

**Issue by enotick** [pa11y/pa11y-dashboard#268]
Hello, 
I browsed the internet and it seems like there is no way to add basic authentication to view dashboard. It would be nice to at least password protect it something similar to htaccess authentication. Even better if we could set permissions on add / edit URLs actions. 

Is it currently possible or am I missing something?

**Comment by josebolos** [comment]
Hi @enotick,

This is a functionality that pa11y-dashboard doesn't support and we don't have plans to add.

That said, if should be possible to set up Apache or any other web server with HTTP basic authentication enabled as a proxy in front of pa11y.

I hope that it helps!
