### ISSUE TITLE
Allow editing of tasks

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y-dashboard#3]
This isn't as simple as it seems; there are a couple of questions to discuss:
1. Will it be confusing/misleading to see sudden drops in number of errors (for example, if somebody adds some ignore rules to an existing task)
2. Do we want to log changes to a task, to allow people to easily see when something changed? If so, how should this look?
3. Is this required, or would it be better to just create a new task? If we do this, would it make sense to be able to "archive" old tasks, in order to give them less prominence in the interface?

**Comment by rowanmanning** [comment]
1. might be, let's do it and test it. Could later be solved by annotations
2. yes, probably a good idea to log. See below for annotations idea
3. yes, we're doing this

``` js
// Annotations idea
annotations: [
    { type: "edit", date: "2013-11-27", comment: "Edited ignore rules" }
]
```

**Comment by perryharlock** [comment]
All done. Need to add functional tests. @rowanmanning

**Comment by rowanmanning** [comment]
Functional tests done. Will merge into develop
