### ISSUE TITLE
Add some dev fixtures

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y-dashboard#34]
We need to make it a lot easier to see lots of different URLs with results, so that it's easier to see all the styles etc. Also for demo purposes and to get new developers up-and-running quicker.

**Comment by perryharlock** [comment]
Yeah...would be good to see a whole set of 30 days results and maybe 30-40 urls

**Comment by rowanmanning** [comment]
I'll have a go, but I'm already looking at a 30,000-line JSON file (that's just for 6 URLs and ~36 total results)

**Comment by perryharlock** [comment]
Shit sticks….I blame the data architect

**Comment by rowanmanning** [comment]
Added to [pa11y-webservice](https://github.com/nature/pa11y-webservice)
