### ISSUE TITLE
Refactor layout of task results page

### ISSUE THREAD

**Issue by perryharlock** [pa11y/pa11y-dashboard#36]
Move the date selector to the main section above the graph.
Add the current date being shown to the main section above the graph
Add a Results from dd/mm/yyy to the bottom section below the graph as a title.

This will then make the results page clearer that the results being shown (apart from the graph are just from this particular date)

**Comment by rowanmanning** [comment]
This done?

**Comment by perryharlock** [comment]
I'll tell you when it's done.

**Comment by perryharlock** [comment]
@rowanmanning It's done :-P
