### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y-dashboard#4]
What should this be called? "pa11y-web" isn't particularly descriptive in my opinion. Something with "dashboard" in the name might make sense. It doesn't technically _have_ to be pa11y-associated – pa11y is almost just an implementation detail.

Suggestions welcome.

**Comment by dotcode** [comment]
pa11y-dashboard sounds good to me. Want me to rename?

**Comment by rowanmanning** [comment]
Cool sounds good. @perryharlock? Maybe leave it until next week – this is going to sound a bit lazy, but renaming directories will take me out of the flow right now ;)

**Comment by perryharlock** [comment]
@rowanmanning @dotcode Yep all cool beans here

**Comment by dotcode** [comment]
Sorted - give me a shout when you're ready and I shall wave my magic wand.

**Comment by dotcode** [comment]
Done.
