### ISSUE TITLE
Add more info to the footer

### ISSUE THREAD

**Issue by perryharlock** [pa11y/pa11y-dashboard#44]
Not sure what...just more info.
e.g. if you want to contribute link
license info
version info

**Comment by perryharlock** [comment]
Change pa11y link to be pa11y-dashboard
Change license to be pa11y-dashboard
Add version info
Style links

**Comment by perryharlock** [comment]
@rowanmanning - Check it if you like. Nothing special.
https://github.com/nature/pa11y-dashboard/commit/8fc041ff3e49a4942b3ba36ffafd4a912fa816dc

**Comment by rowanmanning** [comment]
Looks good
