### ISSUE TITLE
Warn user if they try to run pa11y for a url on a date where a result already exists

### ISSUE THREAD

**Issue by perryharlock** [pa11y/pa11y-dashboard#46]

**Comment by rowanmanning** [comment]
Could this be simplified so that the "Run" button says "Run again" or something if it's already been run that day? Could be a quicker way of getting this done.

**Comment by rowanmanning** [comment]
Going to close this as no users have expressed confusion about it. We can revisit how tasks are run in Pa11y Sidekick, and this _may_ be a bunch of work for relatively little impact at the mo :)
