### ISSUE TITLE
Graph Label Styling

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y-dashboard#51]
When there are lots of results in the graph, the date labels become less readable. See screen-shot:

![Graph With Many Results](https://f.cloud.github.com/assets/138944/1427553/53931b96-408d-11e3-8df4-3a237e563bf1.png)

What could we do to resolve this?

**Comment by perryharlock** [comment]
Changes made from categories to time for x axis..need to get up and running on test area to test large number of entries. @rowanmanning

**Comment by rowanmanning** [comment]
Done
