### ISSUE TITLE
Y axis graph labelling

### ISSUE THREAD

**Issue by dotcode** [pa11y/pa11y-dashboard#57]
![screen shot 2013-11-18 at 23 18 30](https://f.cloud.github.com/assets/1267506/1568070/82b7e3d6-50a8-11e3-9487-7ce6752c0b50.png)

At the moment the graph labels the y axis with floating point units, which doesn't make sense, because you can't get 3.8 accessibility errors :)

Could we alter so that it displays integers instead?

**Comment by perryharlock** [comment]
Fixed - @rowanmanning - can you check?
https://github.com/nature/pa11y-dashboard/commit/7c2647653d29e25ec3af42928bcafedf0e788cd0

**Comment by rowanmanning** [comment]
Looks good
