### ISSUE TITLE
Integrate with HTML CodeSniffer

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y-dashboard#59]
It would be great if you could (with one click) view results with HTML CodeSniffer in-browser. This would increase pa11y's usefulness a lot.

**Comment by alastc** [comment]
Really interesting looking project, I'm not an expert in (or even user of) node.js etc but I got it running on my laptop.

The main thing in terms of use was in the issue listing: If you look at X number of errors on a page, where were they?

There needs to be some way of going from the results to looking at the issue. If HTML code sniffer integration does that, great, but _something_  is needed to go from listing an error to looking at it. Even HTML/CSS line numbers in the output code would help, or an xpath style location, or something that integrates with browser based dev tools.

**Comment by rowanmanning** [comment]
Hi Alastair, glad to hear you got this working :)

Your issue is exactly what we're trying to tackle with this. This is quite high priority, as it would really increase how useful pa11y-dashboard is. In the meantime, you can use [HTML CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) on a page to get the same errors with some context (we're using HTML CodeSniffer behind the scenes to generate our reports).

**Comment by vishal918** [comment]
Hi , Is it possible to integrate HTML Code Sniffer directly in a website without using browser extension?

**Comment by adelevie** [comment]
This would be incredibly useful.

**Comment by jasonday** [comment]
What is the status of this feature?
Any reason for focus on HTML codesniffer, versus other ways of identifying/flagging errors in the DOM (WAVE toolbar approach, etc.)?

**Comment by rowanmanning** [comment]
Hi @jasonday, this isn't being worked on right now, and not sure if it will be any time soon. I did some investigation work into it and there's not really a way to trigger a bookmarklet on a page that you don't control.

The reason for the focus on HTML CodeSniffer is that it's what Pa11y uses under the hood and gives the same results in a visual way.

**Comment by jasonday** [comment]
Thanks for clarifying, @rowanmanning. 
I'm now finding myself further confused, as the dashboard reports that there is the existence of errors, but does not identify what/where those issues are - is there any track of work to include a more robust reporting mechanism?

**Comment by adelevie** [comment]
You can get the CSS selector in your reports, which should help pinpoint where the error is. FWIW, HTML Code Sniffer UI does this pretty well.

**Comment by jasonday** [comment]
@adelevie The dashboard demo export does not include any identification. Can it be updated so that the demo is accurate?

**Comment by badtant** [comment]
Just set up the dashboard and got quite disappointed that I don't get any indication on where in the code the error/warning is.
@adelevie how can I see what you describe?

**Comment by hollsk** [comment]
@badtant I agree, we should really be displaying the selectors on the dashboard. I see you've added a +1 to #85 which asks for just that, please follow that issue for updates. In the meantime, you can see the relevant selector for each item using adelevie's method - download the JSON/CSV report. 

@jasonday - I've raised #112 to update the demo, good catch.

**Comment by rowanmanning** [comment]
I'm afraid this feature won't be making it into Pa11y Dashboard. It would require a significant amount of work, and may not even be possible with the way that Pa11y runs right now. We _can_ however try to work out if this is a possibility in [Pa11y Sidekick](https://github.com/pa11y/sidekick/blob/master/PROPOSAL.md). If you'd like this feature, then please do go over there and raise an issue :) 

I think we've covered the other problems people were having in here (thanks @hollsk for opening separate issues 👍).
