### ISSUE TITLE
Ability to Login

### ISSUE THREAD

**Issue by alvincrespo** [pa11y/pa11y-dashboard#62]
Is there a utility that we can utilize that would allow us to login into an application and check pages that are behind authentication of a user?

**Comment by rowanmanning** [comment]
Hi Alvin, this is currently possible in [pa11y](https://github.com/nature/pa11y) on the command line, and we'll definitely look at exposing this feature in the dashboard in a later release. Thanks

**Comment by andrewmee** [comment]
Hi @alvincrespo, HTTP basic user authentication has now been added in [1.5.0](https://github.com/nature/pa11y-dashboard/tree/1.5.0).

**Comment by qaDream77** [comment]
How do i login on the command line with pa11y?
