### ISSUE TITLE
Add descriptions to ignore rules

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y-dashboard#7]
This can be accessed using `{{description}}`. I don't know what's best for this, maybe as a title attribute or something? Your call

**Comment by perryharlock** [comment]
I'm thinking a title attribute yeah. And then maybe for the js enabled a tooltip or something @rowanmanning?

**Comment by rowanmanning** [comment]
Yeah, sounds sensible to me

**Comment by perryharlock** [comment]
Done and done
