### ISSUE TITLE
Different result when using the bookmarklet

### ISSUE THREAD

**Issue by marcuslindblom** [pa11y/pa11y-dashboard#80]
It seems like the dashboard doesn't use the same tests as the bookmarklet? This is the errors from the same site.
![screen shot 2014-10-05 at 17 28 11](https://cloud.githubusercontent.com/assets/319720/4518893/7df76e0e-4ca4-11e4-8ec4-264ce3d9c397.png)
![screen shot 2014-10-05 at 17 28 27](https://cloud.githubusercontent.com/assets/319720/4518894/812944d0-4ca4-11e4-8300-266c6fc8567e.png)

**Comment by davidmorabito** [comment]
Hey Marcus, did you solve this issue? I'm facing same problem here.
