### ISSUE TITLE
Postgres Support

### ISSUE THREAD

**Issue by adelevie** [pa11y/pa11y-dashboard#81]
I might want to add this feature. Would it be welcomed?

**Comment by rowanmanning** [comment]
As in adding postgres as an alternative data store over MongoDB? Sure, it might have to live in a branch in the short-term but I'd be happy to point people at it and support it.

It's worth noting that after the release of pa11y 2.0 the dashboard is also due a big overhaul. This may involve a change of data store too. Would be delighted to get your input.

**Comment by rowanmanning** [comment]
I just found this issue again! OK definitely not gonna be added in Pa11y Dashboard/Webservice, but we're almost certainly using PostgreSQL for [Pa11y Sidekick](https://github.com/pa11y/sidekick/blob/master/PROPOSAL.md#outline). Going to close :)
