### ISSUE TITLE
Could not connect to pa11y-webservice

### ISSUE THREAD

**Issue by dreamzmaster** [pa11y/pa11y-dashboard#82]
Hi,

I am trying to setup the dashboard and everytime I runt he dashboard it throws the below error:

```
Error: Could not connect to pa11y-webservice
    at Object.handle (/opt/dashboard/pa11y-dashboard/app.js:110:10)
    at next (/opt/dashboard/pa11y-dashboard/node_modules/express/node_modules/connect/lib/proto.js:188:17)
    at pass (/opt/dashboard/pa11y-dashboard/node_modules/express/lib/router/index.js:110:24)
    at nextRoute (/opt/dashboard/pa11y-dashboard/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/opt/dashboard/pa11y-dashboard/node_modules/express/lib/router/index.js:167:11)
    at callbacks (/opt/dashboard/pa11y-dashboard/node_modules/express/lib/router/index.js:161:37)
    at param (/opt/dashboard/pa11y-dashboard/node_modules/express/lib/router/index.js:131:11)
    at pass (/opt/dashboard/pa11y-dashboard/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/opt/dashboard/pa11y-dashboard/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/opt/dashboard/pa11y-dashboard/node_modules/express/lib/router/index.js:167:11)
```

Can you please suggest what's going on.

Thanks

**Comment by rowanmanning** [comment]
Hi @dreamzmaster, could you give me a little more information about your setup?
- OS name/version
- Node.js version
- pa11y-dashboard version

Could you also paste in the full console output around the error?

Thanks

**Comment by tom-oneill** [comment]
Hi @rowanmanning,

I'm having the same issue as above. The version of node I'm using is 0.10.29 and pa11y-dashboard version is 1.5.0. I'm trying to get this running on a Windows 7 machine.

Any suggestions?

Cheers

**Comment by dreamzmaster** [comment]
Hi,

issues was fixed by using mongoDB version 2.6

Cheers!

**Comment by tom-oneill** [comment]
Hi @dreamzmaster,

Downloaded version 2.6 and still getting the same error. Is there any config that I'm missing?

Cheers

**Comment by RicCarey** [comment]
Having the same issue as @tom-oneill 

I downgraded mongo to 2.6 but still get the same issue. where there any additional steps @dreamzmaster 

cheers

**Comment by RicCarey** [comment]
Got it working @tom-oneill or anyone who run into the same issue, i think it would be worth adding this info to the Docs. 

Basically MongoDB needs to be running at the same time, as the NODE_ENV=production node . command is run. 

So i followed the instructions on https://docs.mongodb.org/getting-started/shell/tutorial/install-mongodb-on-linux/ then in one comand prompt ran mongod --dbpath=/data/db and then in another ran NODE_ENV=production node . 

and then it kicked into life. I believe that the next step will be to get the mongodb running as a service rather than in a command.

**Comment by tom-oneill** [comment]
Thanks @RicCarey that did the trick and got the dashboard up and running. It doesn't seem to be able to run any tests however. I can set up my urls but when I run pa11y nothing happens.

```
Failed to finish task 55b8e17.....: undefined is not a function
```

Have you come across this?

**Comment by rowanmanning** [comment]
@RicCarey thanks for pointing out. Yes MongoDB needs to be running at the same time, and this isn't clear enough in the docs. I can look at addressing this, also happy if you want to open a PR :)

@tom-oneill is every task failing to finish? Have you tried adding some URLs like `google.com`? I don't think I've come across that error before myself.

**Comment by mgifford** [comment]
What I was stuck by was that I needed to take extra steps to actually have mongodb running:

https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/#run-mongodb

I had assumed I'd just need to install it and we'd be good to go...

Better errors and documentation would be useful.

**Comment by syndy1989** [comment]
Hi,
I'm new to pa11y and i wanted to check multiple URL's using pa11y-webservice.

OS nam: Windows
Node.js version:4.6.0
pa11y-dashboard version:1.5.0
mongo db version:3.4

i followed the instructions on https://github.com/pa11y/webservice#setup but i'm not quite sure how to setup the environment variables and modify the config files to make it work.
Any advise would be helpful.Thanks in advance

**Comment by josebolos** [comment]
Hi @syndy1989 

This is an old issue that was closed long ago. Would you mind creating [a new Issue](https://github.com/pa11y/dashboard/issues/new) describing your problem, please?

Thanks!

**Comment by syndy1989** [comment]
Sure . Thanks @joseluisbolos
