### ISSUE TITLE
Url validator

### ISSUE THREAD

**Issue by debugwand** [pa11y/pa11y-dashboard#83]
Validate URLs so that people can't do stupid things like only putting one slash after http (ahem)

**Comment by rowanmanning** [comment]
Hey Dawn. Currently I _think_ the URL entries are `<input type="url"/>`. If not, then this could definitely be helpful. Worth somebody testing out anyway!

**Comment by frvge** [comment]
Found this for input type="url":

> This time the minimum requirement for most browsers is one or more letters followed by a colon.

Of course that's not really useful. I'll make a PR in a few moments with some better validation.
