### ISSUE TITLE
Display error's location

### ISSUE THREAD

**Issue by Simounet** [pa11y/pa11y-dashboard#85]
Hi there,

Did I miss something or it is not possible to display error's location on the dashboard log? When I use pa11y command line, I can see where fixes need to be done.

Have a nice day.

**Comment by badtant** [comment]
+1

**Comment by hollsk** [comment]
This was added in this update: https://github.com/springernature/pa11y-dashboard/pull/100

Please pull down the latest Dashboard version if you haven't already!
