### ISSUE TITLE
Authenticated editors?

### ISSUE THREAD

**Issue by noqcks** [pa11y/pa11y-dashboard#87]
I have this use case. I would only like adding sites to be allowed by a certain number of users. But as is there is only the option to allow everyone to edit sites, or no one. 

Is there any future plans to support some kind of authentication for editing sites?

**Comment by rowanmanning** [comment]
There are no immediate plans to do this, as it would introduce a considerable amount of extra complexity. In the short term, you could feasibly do this if you run the dashboard behind nginx or similar, and rely on basic auth to deny access to the edit pages. You'd still see buttons, but unauthenticated users would get a 401

**Comment by noqcks** [comment]
Yeah, I was hoping to do outside of nginx, as putting basic auth just on edit pages is kind of a gross work around imo.

Thanks for your help.
