### ISSUE TITLE
Better icons for the expand/collapse controls

### ISSUE THREAD

**Issue by simevidas** [pa11y/pa11y-dashboard#88]
I’m looking at a demo on pa11y.org. The Errors, Warnings, Notices bars can be expanded by clicking on the `+` character on the right. I don’t think this is a good choice for such a control. I initially thought it was a control for _adding_ something. (Add an error? What?). I think, up/down arrows (▼ and ▲, or similar) are better choices. You could also label the controls with “Expand” and “Collapse”, to “exterminate” any potential confusion.

**Comment by rowanmanning** [comment]
Good point, @simevidas! For anyone who wants to contribute, this might be a good starter issue :) someone on the core team will be happy to help anyone who's new to open source.

**Comment by hollsk** [comment]
@howlingmad where can we find the fancy arrows that you suggested would be good for this?

**Comment by j-mes** [comment]
Would it be referring to [HTML Arrows](http://htmlarrows.com/arrows/)? I would be very happy to do this with guidance of course.
