### ISSUE TITLE
Add graph to home page showing average of all tasks errors, warnings and notifications.

### ISSUE THREAD

**Issue by perryharlock** [pa11y/pa11y-dashboard#9]
As a user 
When on the home page
Then I want to see a graph which shows the average of all tasks at the run times.
Then if no javascript a table with the averages needs to be shown

**Comment by Hywan** [comment]
:+1:

**Comment by Hywan** [comment]
I consider the project still active. Do you have time to implement this feature? If yes, can you estimate the time to get it merged? Thanks!

**Comment by rowanmanning** [comment]
Unfortunately we won't have time/capacity to implement this in Pa11y Dashboard. It'd be a considerable amount of work and I also think it may not be useful for a lot of people without the ability to group URLs (a lot of people use Pa11y Dashboard to test multiple websites).

However, there's good news! I really want to get this feature into Pa11y Sidekick, [there's a comment here](https://github.com/pa11y/sidekick/issues/15#issuecomment-220768113) which you should go and reply to if this is a feature you care about :)
