### ISSUE TITLE
Keyboard accessibility: results page

### ISSUE THREAD

**Issue by dotcode** [pa11y/pa11y-dashboard#91]
On the results page (i.e. http://demo.pa11y.org/52457e2b135a4b51b4000001) there is no way to access the controls (e.g. the errors/warnings/notices links, the calendar) with a keyboard.

**Comment by alexkilgour** [comment]
Cannot replicate this issue. Waiting for more information.

**Comment by patrickhlauke** [comment]
taking http://demo.pa11y.org/52382f4ac0d6c9ac49000006 as a meatier example:
- open page,
- using TAB, navigate to the date dropdown (6 TABs)
- cursor down and/or ENTER open the dropdown, but not possible to actually select anything with the keyboard (tried using cursor up/down)

ah, just realised now that using TAB it's possible to actually focus different dates. this is counter-intuitive, as it does look/behave like a `<select>`. confusing for a sighted keyboard user (not cracked open a screen reader yet to test if it announces it in a more sensible/understandable way there).

however, moving on from there: keep tabbing to try and get to the "+" controls to open the "Warnings" and "Notices" disclosure panels. not possible. and if the first panel "Errors" was previously closed (say with the mouse), not possible to open it either. (and conversely of course, not possible to close those panels with the keyboard either).

**Comment by patrickhlauke** [comment]
so as example for the disclosure widget triggers, these two

```
<div class="heading label-danger showing first" id="errors" data-test="task-errors">
  <span data-role="expander" class="pull-right expander"> - </span>
  Errors ( 3 )
</div>
...
<div class="heading label-warning" id="warnings" data-test="task-warnings">
  <span data-role="expander" class="pull-right expander"> + </span>
  Warnings ( 1 )
</div>
```

should probably be something more like

```
<div class="heading label-danger showing first" role="button" tabindex="0" aria-expanded="true" aria-controls="[give the related panel an id, then refer to it from here]" id="errors" data-test="task-errors">
  <span data-role="expander" class="pull-right expander" aria-hidden="true"> - </span>
  Errors ( 3 ) <span class="hidden-accessible">(collapse this panel)</span>
</div>
...
<div class="heading label-warning" role="button" tabindex="0" aria-expanded="false" aria-controls="..." id="warnings" data-test="task-warnings">
  <span data-role="expander" class="pull-right expander" aria-hidden="true"> + </span>
  Warnings ( 1 ) <span class="hidden-accessible">(expandthis panel)</span>
</div>
```

with the `.hidden-accessible` class being something that visually hides the content without removing it from the DOM

**Comment by patrickhlauke** [comment]
doh, forgot to make them focusable...fixed now/updated comment

**Comment by patrickhlauke** [comment]
(alternatively, use a real `<button>` instead of `<div role="button" tabindex="0">`+custom key handling JS, of course)

**Comment by alexkilgour** [comment]
Thanks for the extra information, this makes more sense now
