### ISSUE TITLE
Cannot make it run

### ISSUE THREAD

**Issue by r3m4k3** [pa11y/pa11y-dashboard#95]
When I'm trying to run grunt start-test I'm getting this error:

pa11y-dashboard-master/app.js:38
    app.express = express();
                  ^

TypeError: express is not a function

Any help would be appreciated.
What am I doing wrong?

**Comment by rickymuvel** [comment]
it's
app = express();

**Comment by GlynnPhillips** [comment]
Hi @r3m4k3, could you provide some more info please? OS, Node version, etc?

Can you try removing your node modules folder (`rm -rf node_modules`) and reinstalling (`npm install`)

Thanks

**Comment by rowanmanning** [comment]
Hi @r3m4k3: there have been a load of updates recently and we're trying to make it easier to work out what's wrong if you can't get the dashboard running (For a start, we've stopped using Grunt to run the app).

I'm going to close this for now, but if you're still having the issue with the latest version of the dashboard (version `1.12.0` as of writing) then we can reopen and try to help :)
