### ISSUE TITLE
Differences in error counts between pa11y dash results and HTML_CodeSniffer

### ISSUE THREAD

**Issue by andrew-fowler** [pa11y/pa11y-dashboard#97]
Hi there, 

If I run a pa11y dash job against google.com using WCAG2AA, I get 1 error, 14 warnings and 41 notices.

If I run the HTML_CodeSniffer bookmarklet against google.com using WCAG2AA, I get 11 errors, 23 warnings and 79 notices.

Trying other sites seems to show a similar disconnect.

On the face of it, I'd expect the results for both to be the same.  I've not looked at the code much yet (my js skills leave something to be desired) but is this the expected behaviour?  

Thanks,
Andrew

**Comment by nickcall** [comment]
Hi @andrew-fowler, We’ve had a couple of issues raised along similar lines to this so we did some analysis on why there can be differences between Pa11y/Pa11y dashboard and the HTML CodeSniffer bookmarklet.

We’ve documented the differences and reasons for them in the common questions https://github.com/pa11y/pa11y/blob/master/README.md#common-questions section of the Pa11y readme.

Hope that helps.
